export const GET_CAMPAIGNS_LOADING = "GET_CAMPAIGNS_LOADING";
export const GET_CAMPAIGNS_ERRORS = "GET_CAMPAIGNS_ERRORS";
export const GET_CAMPAIGNS_SUCCESS = "GET_CAMPAIGNS_SUCCESS";

export const GET_TEAMS_LOADING = "GET_TEAMS_LOADING";
export const GET_TEAMS_ERRORS = "GET_TEAMS_ERRORS";
export const GET_TEAMS_SUCCESS = "GET_TEAMS_SUCCESS";
